### ISSUE TITLE
arcore-sdk errors when imported to unity 

### ISSUE THREAD

**Issue by sherzodkh** [google-ar/arcore-unity-sdk#550]
### SPECIFIC ISSUE ENCOUNTERED
unity console shows bunch of errors when arcore-sdk is imported 

### VERSIONS USED
- Unity: 2019.1.0f2
- ARCore SDK for Unity: 1.8.0
- Device manufacturer, model, and O/S: Windows 

### STEPS TO REPRODUCE THE ISSUE
 1. unity console shows errors when sdk is imported into unity 

### ADDITIONAL COMMENTS

![unity-arcore-error](https://user-images.githubusercontent.com/29689538/56987809-e4921480-6ba7-11e9-8e2e-56b6c73179ea.png)

**Comment by dhvl5** [comment]
> ### SPECIFIC ISSUE ENCOUNTERED
> unity console shows bunch of errors when arcore-sdk is imported
> 
> ### VERSIONS USED
> * Unity: 2019.1.0f2
> * ARCore SDK for Unity: 1.8.0
> * Device manufacturer, model, and O/S: Windows
> 
> ### STEPS TO REPRODUCE THE ISSUE
> 1. unity console shows errors when sdk is imported into unity
> 
> ### WORKAROUNDS (IF ANY)
> ### ADDITIONAL COMMENTS
> ![unity-arcore-error](https://user-images.githubusercontent.com/29689538/56987809-e4921480-6ba7-11e9-8e2e-56b6c73179ea.png)

Please fix it, I'm having this problem too

**Comment by marklinmao** [comment]
Same problem here! Any workaround, please???

**Comment by sherzodkh** [comment]
deleted Unity 2019 and download Unity previous version 2018.3.14f1 and it's working fine now.

**Comment by sam598** [comment]
I was having the same issue and found a way to get it to work in 2019.1.2

1) Start a new project and set the build target to Android.
2) Close Unity.
3) Copy and paste the ARCore Assets and Settings folders into the new project.
4) Open the project in Unity.
5) There will be errors, ignore those for now.
6) Under "Project Settings > Player > Scripting Runtime Version" change it to ".NET 4.x Equivalent"
7) Restart Unity when prompted.

This has worked twice, though I have no idea why this specific order of events works. Doing it in any other order results in a project that cannot be fixed.

**Comment by AttikaMayou** [comment]
Hello @sam598 
Thanks for the workaround. 

I'm actually using Unity 2019.1.2f1 and tried your steps. Since my "Scripting Runtime Version" is already set to "NET 4.x Equivalent" when I start a new project, I tried to set it "NET 3.5 Equivalent" and reset it to 4.x but it won't fix my errors (the same 15 errors in the initial post up here). Any clue ? 
I think that maybe I didn't copy-paste the right folders (step 3). Could you give more precisions please ?

**Comment by sam598** [comment]
@AttikaMayou 

When I started a new project it is set to "NET 4.x Equivalent". For some reason it gets set to "NET 3.5 Equivalent" between steps 3 and 4.

I have no idea why this specific series of steps works, but it has worked twice for me. Doing them in any other order has led to a project that I cannot fix.

**Comment by AttikaMayou** [comment]
Thanks for the quick reply @sam598 !

I'll go back to Unity 2018.3.12f1 since even with the ARCore v1.8.0, I can't get it to work with Unity 2019.1.2f1 :(

**Comment by CGstunts** [comment]
Same here

**Comment by LaVraieVicotte** [comment]
Maybe it could help some ! I had the same error messages yesterday and the solution for Unity 2019 was to do:
Window> Package Manager to install the HLAPI and XR Multiplayer Legacy Input Helpers packages.

**Comment by TheBricktop** [comment]
unity 2019.1.4 problems still persist.

**Comment by anficyon** [comment]
unity 2019.1.8 same problem, I wanted to develop ;(

**Comment by knightcube** [comment]
unity 2019.1.10f1 same problem

**Comment by NocturnalWisp** [comment]
Unity v2019.2.0f1 & ARCore v1.11 still persists with this problem.

**Comment by Clyorath** [comment]
Hey, this just solved this problem for me!

For Unity 2019 you have to include the packages "Multiplayer HLAPI" and "XR Legacy Input Helpers". 

My source:
https://developers.google.com/ar/develop/unity/enable-arcore

 **Import the ARCore SDK for Unity**
 
 Download the ARCore SDK for Unity and import it into your project by clicking the menu Assets > Import package > Custom Package. **(Unity 2019 only:** To fix the compilation errors, use **Window > Package Manager** to install the **Multiplayer HLAPI** and **XR Legacy Input Helpers** packages.)

**Comment by SanketPanda** [comment]
> Hey, this just solved the problem for me!
> 
> For Unity 2019 you have to include the packages "Multiplayer HLAPI" and "XR Legacy Input Helpers".
> 
> My source:
> https://developers.google.com/ar/develop/unity/enable-arcore
> 
> **Import the ARCore SDK for Unity**
> 
> Download the ARCore SDK for Unity and import it into your project by clicking the menu Assets > Import package > Custom Package. **(Unity 2019 only:** To fix the compilation errors, use **Window > Package Manager** to install the **Multiplayer HLAPI** and **XR Legacy Input Helpers** packages.)
> 
> I hope this helps!

Thank you it is working fine.

**Comment by AntonyJeeva** [comment]
> Hey, this just solved the problem for me!
> 
> For Unity 2019 you have to include the packages "Multiplayer HLAPI" and "XR Legacy Input Helpers".
> 
> My source:
> https://developers.google.com/ar/develop/unity/enable-arcore
> 
> **Import the ARCore SDK for Unity**
> 
> Download the ARCore SDK for Unity and import it into your project by clicking the menu Assets > Import package > Custom Package. **(Unity 2019 only:** To fix the compilation errors, use **Window > Package Manager** to install the **Multiplayer HLAPI** and **XR Legacy Input Helpers** packages.)
> 
> I hope this helps!

yo it fixed my error
thanks

**Comment by adityaspt** [comment]
> Hey, this just solved the problem for me!
> 
> For Unity 2019 you have to include the packages "Multiplayer HLAPI" and "XR Legacy Input Helpers".
> 
> My source:
> https://developers.google.com/ar/develop/unity/enable-arcore
> 
> **Import the ARCore SDK for Unity**
> 
> Download the ARCore SDK for Unity and import it into your project by clicking the menu Assets > Import package > Custom Package. **(Unity 2019 only:** To fix the compilation errors, use **Window > Package Manager** to install the **Multiplayer HLAPI** and **XR Legacy Input Helpers** packages.)
> 
> I hope this helps!

Thank you man ! This helped
