### ISSUE TITLE
Examples don't compile with Unity 2018.2 beta

### ISSUE THREAD

**Issue by brookman** [google-ar/arcore-unity-sdk#197]
`UnityEngine.Network' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'

**Comment by pablisho** [comment]
Hi, thanks for the bug report. I added to our internal tracking to fix it for next releases.

**Comment by vCillusion** [comment]
I modified my code to below instead of using `Network.player.ipaddress`.

```
    NetworkIdentity m_Identity;
    
    void Start()
    {
        //Fetch the NetworkIdentity component of the GameObject
        m_Identity = GetComponent<NetworkIdentity>();

        //Output to the console the connection associated with this NetworkIdentity
        Debug.Log("Connection : " + m_Identity.connectionToClient);
    }
```

**Comment by vengababu7** [comment]
hai vCillusion thanks, to use your code do i need to import(using) anything.

**Comment by vCillusion** [comment]
I have updated my answer to include import statement. Hope it helps!

**Comment by vengababu7** [comment]
Thank VCilllusion 👍

**Comment by vitorfreire** [comment]
Hello! I don't understand which script I should edit.

**Comment by castana1962** [comment]
Hi pablisho
I am having the same error in Unity 2018.2 beta and Photon Unity Networking unitypackage downloaded from Unity Assets Store
Assets/Photon Unity Networking/Editor/PhotonNetwork/PhotonEditor.cs(675,46): error CS0619: `UnityEngine.RPC' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'
For it and sorry for my little English but Was this error fixed ? If it is like that Could you say me where I could get this last Photon Unity Networking unitypackage?
Thanks for your time
Alejandro

**Comment by FDDdan** [comment]
Same problem with ARCore 1.4.0 and Unity 2018.2.1f1. I've managed to make the Hosting work, by using vCillusion fix and pshah123 patched scripts (#310), but I can't Resolve because the IP address showing is always 192.0.0.1. Any workaround to get the device IP Address?

**Comment by paragbhagwat3575** [comment]
Google: Can you please provide a detailed way of how yo fix this. A fix was mentioned above but its unclear which script one needs to modify.

**Comment by FUBAR2077** [comment]
Hello, ip address is just for showing it on scene UI, nothing more, you can just comment this line:
            IPAddressText.text = "My IP Address: ";
            //IPAddressText.text = "My IP Address: " + Network.player.ipAddress;
Sort of quick fix until ARCore team doesn't fix it up on their side for people who don't really make use of Cloud Anchors for now.

**Comment by Avinashranjan21** [comment]
@paragbhagwat3575  Goto Assest ->GoogleARCore->Examples->CloudAnchors->Scripts-> Open CloudAnchorUIController in editor.
Then paste below code in import statement

```
using UnityEngine;
using UnityEngine.Networking;
```
Then go down you will find start method just replace it with below code

```
NetworkIdentity m_Identity;
    
    void Start()
    {
        //Fetch the NetworkIdentity component of the GameObject
        m_Identity = GetComponent<NetworkIdentity>();

        //Output to the console the connection associated with this NetworkIdentity
        Debug.Log("Connection : " + m_Identity.connectionToClient);
    }
```
And you are good to go :)

**Comment by pablisho** [comment]
Hi, this issue has been fixed in [ARCore SDK for Unity v1.4.1](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.4.1). Feel free to comment if you still experience issues with 2018.2
